### ISSUE TITLE
How to improve the performance

### ISSUE THREAD

**Issue by ZJU-lishuang** [triton-inference-server/model_analyzer#360]
I test the yolov5n model in triton.
But the model performance is bad.
How to improve it?Like `perf_analyzer --shared-memory cuda`.
This is my report.
[result_summary.pdf](https://github.com/triton-inference-server/model_analyzer/files/8401999/result_summary.pdf)

[detailed_report.pdf](https://github.com/triton-inference-server/model_analyzer/files/8402000/detailed_report.pdf)

the performance is worse than the [DeepLearningExamples](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/Classification/ConvNets/triton/resnet50#online-nvidia-t4-onnx-runtime-tensorrt-with-fp16)

**Comment by Tabrizian** [comment]
It looks like the model that you are profiling (YOLOv5) is different from the model in the Deep Learning Examples repository (ResNet50) so the performance could be different.

**Comment by tgerdesnv** [comment]
What version of Model Analyzer are you using? It looks old. The latest version of Model Analyzer will also sweep the model's max batch size, which may provide improvements for your case.

**Comment by tgerdesnv** [comment]
@ZJU-lishuang in version 21.08, by default Model Analyzer sorted by latency. Newer versions will sort by throughput by default. 

In order to have it sort by throughput, there are two options. 
- Run analyze/report steps in ['offline'](https://github.com/triton-inference-server/model_analyzer/blob/main/docs/cli.md#offline-mode) mode:  `model-analyzer -m offline analyze ...`
- Set the [objectives](https://github.com/triton-inference-server/model_analyzer/blob/68aaf1380014f39a0a2328b1beec49c78b0f6599/docs/config.md#objective) to perf_latency_p99. Note that this can only be done via the yaml config file and not the command line.

**Comment by ZJU-lishuang** [comment]
I will try version 22.03.
