### ISSUE TITLE
How to get gpu_used_memory in perf_analyzer

### ISSUE THREAD

**Issue by hannan72** [triton-inference-server/model_analyzer#373]
Hi,
Currently I'm working with the model analyzer and I need to find the GPU allocated memory for the models. However, in the `latency-report-file` only the latency reports are existed. Is there any way that we can also report the gpu metrics?

My concern is about the models with dynamic input shape and I need to find the latency and also gpu allocated memory for different input lengths.

**Comment by Tabrizian** [comment]
Perf Analyzer doesn't collect the GPU memory data. Is there a reason why you want to get the GPU memory information from Perf Analyzer instead of Model Analyzer? Some frameworks like Tensorflow do not release the memory that they have allocated during inferencing which may lead to misleading results. For example, if you start inferencing with large inputs and later use smaller inputs, the memory usage might be still the same.  Model Analyzer in local and docker mode restarts the Triton server to make sure that the memory usage is properly reported.

**Comment by hannan72** [comment]
Thanks a lot for your complete answer @Tabrizian 
At the first place, when I was changing the input shape, it doesn't affect the allocated memory. My first assumption was that the input shapes are just considered in Perf analyzer. However, accidentally after a while my problem got solved and the allocated memory reported by the model analyzer got real values by changing the input shape.
