### ISSUE TITLE
[Bug] failed to load 'maxvit_rmlp_base', failed to poll from model repository (model_output path is the same)

### ISSUE THREAD

**Issue by bitchaser12** [triton-inference-server/model_analyzer#852]
I've been trying to run model_analyzer but I've been having issues. I followed the documentation exactly and I was re-reading these threads over and over but I still can't get it to work:
https://github.com/triton-inference-server/model_analyzer/issues/786
https://github.com/triton-inference-server/model_analyzer/issues/789
https://github.com/triton-inference-server/model_analyzer/issues/120

Here is my docker command:
`docker run -it --gpus all -v /var/run/docker.sock:/var/run/docker.sock -v ${pwd}:/workspace -v /model_out:/model_out --net=host nvcr.io/nvidia/tritonserver:24.03-py3-sdk`

Here is my model_evaluator command:
`model-analyzer profile -f perf.yaml --triton-launch-mode=docker`
Here is my perf.yaml:
`model_repository: /workspace/model_repository
profile_models: maxvit_rmlp_base
output_model_repository_path: tmp/model_out
triton_launch_mode: local
override_output_model_repository: true
latency_budget: 10
run_config_search_mode: quick`

and here is the error:
`[Model Analyzer] Model maxvit_rmlp_base_config_default load failed: [StatusCode.INTERNAL] failed to load 'maxvit_rmlp_base', failed to poll from model repository`
If I set the output_model_repository_path to the value I passed into docker for the mount: `output_model_repository_path: /model_out`, then I get a different error:
`FileExistsError: [Errno 17] File exists: '/model_out'`

Any help would be greatly appreciated. I've been re-reading these threads and the documentation for 2 hours now but can't seem to figure this out.

In the server logs I see:
E0329 19:08:15.300700 7 model_repository_manager.cc:1291] failed to poll model 'maxvit_rmlp_base': model not found in any model repository.

**Comment by tgerdesnv** [comment]
Hi @Skier23, sorry for the slow response. I just got back from vacation and have a large backlog of things to look at.

I'm sorry to hear you have had trouble getting this to work. After a quick read of your issue, my guess is that this mount is causing you problems:
`-v ${pwd}:/workspace`

The path needs to be the same on both sides, since you are running on docker mode and thus a docker is being created inside of another docker. Both sides of the mount need to be the same, and need to be absolute paths. Otherwise the internal docker won't be able to see the contents.

**Comment by tgerdesnv** [comment]
Yeah that was back in 2021 before I was working on this. Not sure if that would have worked then, but it won't currently. We have a ticket to detect and at least warn users of this case. 
I'm glad to hear that you got this to work with remote.
Let me know if you have any other feedback or run into any other issues.
